[package]
name = "egld-pay-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.egld-pay]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.35.0"
